version: "3.3"

services:

  database:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=company
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
